//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IJinxService")]
public interface IJinxService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJinxService/Send", ReplyAction="http://tempuri.org/IJinxService/SendResponse")]
    string Send(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJinxService/Send", ReplyAction="http://tempuri.org/IJinxService/SendResponse")]
    System.Threading.Tasks.Task<string> SendAsync(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJinxService/Read", ReplyAction="http://tempuri.org/IJinxService/ReadResponse")]
    string Read();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJinxService/Read", ReplyAction="http://tempuri.org/IJinxService/ReadResponse")]
    System.Threading.Tasks.Task<string> ReadAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IJinxServiceChannel : IJinxService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class JinxServiceClient : System.ServiceModel.ClientBase<IJinxService>, IJinxService
{
    
    public JinxServiceClient()
    {
    }
    
    public JinxServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public JinxServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public JinxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public JinxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Send(string message)
    {
        return base.Channel.Send(message);
    }
    
    public System.Threading.Tasks.Task<string> SendAsync(string message)
    {
        return base.Channel.SendAsync(message);
    }
    
    public string Read()
    {
        return base.Channel.Read();
    }
    
    public System.Threading.Tasks.Task<string> ReadAsync()
    {
        return base.Channel.ReadAsync();
    }
}
